# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a31a2e81a2a76e7116d21797152e30f27e31e781dadb7adc06ee12df2ea9431a93981317002ba8f915890bef8ca3e6836d3a891759a7ec52a088a5b334bcf625

test:
  secret_key_base: a9fb209f949ae6b57af563968d4ff92bc523bbf31e78b55d97958b9dcdc0e5b4ab0d89e55fcc755dd3148a1faa7c49561059d44113353a4ce391dd4b3b91cfb5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
